### ISSUE TITLE
Label alignment tweaks

### ISSUE THREAD

**Issue by andrzejnovak** [cms-cat/cms-root-style#11]
The CMS label when "in-frame" should be aligned in the top left corner with the same distance from both axes. 

![image](https://github.com/cms-cat/cms-root-style/assets/13226500/6a7c29a1-2e44-41d1-a684-22187af88e39)

**Comment by anmalara** [comment]
Sure, I can do that.
It was not the default setting in the "old" TDR style. I kept that code as much as possible.
At the moment, it's set as a fixed fraction of each of the pad lengths.

I can make the fraction equals, this would be safe to have and not depending on the squared/rectangular shapes.
Alternatively, I can give a fix spacing, but has to be large enough to avoid overlaps in any possibility.

**Comment by anmalara** [comment]
addressed in #13

**Comment by ttedeschi** [comment]
PR merged

**Comment by andrzejnovak** [comment]
Sorry to reopen this, but can yo also update the example pdfs with the change?

**Comment by andrzejnovak** [comment]
Yeah, sounds good.

**Comment by ttedeschi** [comment]
I can work on migrating this repo to using LFS now

**Comment by ttedeschi** [comment]
Now the repo is using LFS

**Comment by anmalara** [comment]
See #14.
I fixed it also for the ratio pad.
I also removed the annoying cut of the y-axis when having the ratio pad drawn.

**Comment by ttedeschi** [comment]
https://github.com/cms-cat/cms-root-style/pull/14 merged
