### ISSUE TITLE
Use Git LFS for binary files

### ISSUE THREAD

**Issue by clelange** [cms-cat/cms-root-style#4]
Make sure to rewrite history to get this right from the beginning, specifically for ROOT and graphics files.

**Comment by ttedeschi** [comment]
I am about to push force the history rewriting to use LFS.
@anmalara @linev please confirm that you are not working right now on your forks since you should fork again after the history rewriting

**Comment by anmalara** [comment]
fine for me

**Comment by ttedeschi** [comment]
Done
