### ISSUE TITLE
Avoid overlapping axis labels

### ISSUE THREAD

**Issue by clelange** [cms-cat/cms-root-style#7]
Avoid what's happening with "0.0" at https://cms-analysis.docs.cern.ch/guidelines/plotting/general/#cms-label-position

This can be fixed by moving the labels further away from one of the axes.

**Comment by anmalara** [comment]
Should be fixed for the root plotter in #13.
Examples:
<img width="653" alt="Screenshot 2023-09-27 at 11 29 01" src="https://github.com/cms-cat/cms-root-style/assets/25077363/e5f102b1-5c51-4cda-abe4-ca6e72af9e31">
<img width="779" alt="Screenshot 2023-09-27 at 11 30 20" src="https://github.com/cms-cat/cms-root-style/assets/25077363/c40d6aad-4127-4720-901e-90a07f40343b">

**Comment by ttedeschi** [comment]
PR merged
