### ISSUE TITLE
Place CMS label dynamically

### ISSUE THREAD

**Issue by clelange** [cms-cat/cms-root-style#8]
@IzaakWN said he had a solution for this that would be great to try.

**Comment by IzaakWN** [comment]
Hi @clelange, @anmalara,
This is my modified version of `CMSStyle.py` with a solution for the dynamic placement and scaling of the usual CMS labels. I think you more or less need these for placing the CMS labels outside the frame:
```
  H = pad.GetWh()*pad.GetHNDC()
  W = pad.GetWw()*pad.GetWNDC()
  l = pad.GetLeftMargin()
  t = pad.GetTopMargin()
  r = pad.GetRightMargin()
  b = pad.GetBottomMargin()
  e = 0.025
  scale = float(H)/W if W>H else 1 # float(W)/H
  
  [...]
  
  if iPosX==0:
    relPosX_ = relPosX_*(42*t*scale)*(cmsTextSize/0.84)
    posX = l + relPosX_ #*(1-l-r)
    posY = 1 - t + lumiTextOffset*t
```
Source: https://github.com/cms-tau-pog/TauFW/blob/8984be701ef6a5e4d126a16c390b4efb4afe101a/Plotter/python/plot/CMSStyle.py#L186-L193

Examples of output that shows the dynamic placement works: https://ineuteli.web.cern.ch/ineuteli/forCAT/CMSStyle/

It required some finetuning, and reverse engineering of ROOT's canvas coordinate system... You can test it yourself with these standalone scripts, which should reproduce the plots on my website above:
```
wget https://raw.githubusercontent.com/cms-tau-pog/TauFW/master/Plotter/python/plot/CMSStyle.py
wget https://raw.githubusercontent.com/cms-tau-pog/TauFW/master/Plotter/test/testCMSStyle.py
python3 testCMSStyle.py -v2
```

**Comment by IzaakWN** [comment]
As mentioned in https://github.com/cms-cat/cms-root-style/issues/10, a possible alternative solution are getting the width of "CMS" with one of these methods: [TLaTeX::GetBoundingBox](https://root.cern.ch/doc/master/classTLatex.html#a709b2c2f2858652ce790e6ed0d0cc7ab), [TLaTeX::GetXsize](https://root.cern.ch/doc/master/classTLatex.html#a072e3bccd8193e03b8caa93c63979cd0), but I never tried it...

**Comment by andrzejnovak** [comment]
> Examples of output that shows the dynamic placement works: https://ineuteli.web.cern.ch/ineuteli/forCAT/CMSStyle/

I like these a lot. They already very closely match the style in `mplhep` except having ticks on all sides https://cms-analysis.docs.cern.ch/guidelines/plotting/general/#cms-label-position

If we could sync on this, that would be great!

**Comment by IzaakWN** [comment]
Yes, actually the ticks are missing on all sides are missing because of a bug that I fixed (`pad.SetTicks(1,1)`). This was indeed default in the original TDR style. Lemme update the images.

**Comment by IzaakWN** [comment]
> As mentioned in #10, a possible alternative solution is getting the width of "CMS" with one of these methods: [`TLaTeX::GetBoundingBox`](https://root.cern.ch/doc/master/classTLatex.html#a709b2c2f2858652ce790e6ed0d0cc7ab), [`TLaTeX::GetXsize`](https://root.cern.ch/doc/master/classTLatex.html#a072e3bccd8193e03b8caa93c63979cd0), but I never tried it...

Btw, I could get these methods to work... They all return 0 size... Not sure if I am missing something...
```
import ctypes
w, h = ctypes.c_uint(), ctypes.c_uint()

latex = TLatex()
...
latex.DrawLatex(...,"CMS")
latex.GetBoundingBox(w,h)
print(">>> latex.GetXsize()=%r, latex.GetXsize()=%r"%(latex.GetXsize(),(w.value,h.value)))
```

**Comment by ttedeschi** [comment]
> Hi @clelange, @anmalara, This is my modified version of `CMSStyle.py` with a solution for the dynamic placement and scaling of the usual CMS labels. I think you more or less need these for placing the CMS labels outside the frame:
> 
> ```
>   H = pad.GetWh()*pad.GetHNDC()
>   W = pad.GetWw()*pad.GetWNDC()
>   l = pad.GetLeftMargin()
>   t = pad.GetTopMargin()
>   r = pad.GetRightMargin()
>   b = pad.GetBottomMargin()
>   e = 0.025
>   scale = float(H)/W if W>H else 1 # float(W)/H
>   
>   [...]
>   
>   if iPosX==0:
>     relPosX_ = relPosX_*(42*t*scale)*(cmsTextSize/0.84)
>     posX = l + relPosX_ #*(1-l-r)
>     posY = 1 - t + lumiTextOffset*t
> ```
> 
> Source: https://github.com/cms-tau-pog/TauFW/blob/8984be701ef6a5e4d126a16c390b4efb4afe101a/Plotter/python/plot/CMSStyle.py#L186-L193
> 
> Examples of output that shows the dynamic placement works: https://ineuteli.web.cern.ch/ineuteli/forCAT/CMSStyle/
> 
> It required some finetuning, and reverse engineering of ROOT's canvas coordinate system... You can test it yourself with these standalone scripts, which should reproduce the plots on my website above:
> 
> ```
> wget https://raw.githubusercontent.com/cms-tau-pog/TauFW/master/Plotter/python/plot/CMSStyle.py
> wget https://raw.githubusercontent.com/cms-tau-pog/TauFW/master/Plotter/test/testCMSStyle.py
> python3 testCMSStyle.py -v2
> ```
@IzaakWN do you think you can create a Pull Request with your modifications?

**Comment by ttedeschi** [comment]
Sorry @IzaakWN, any news on this?

**Comment by IzaakWN** [comment]
Hi @ttedeschi, yes, I just discussed it with @anmalara, and he agreed to try it out.

**Comment by anmalara** [comment]
Thanks, @IzaakWN for the tip.
I've implemented it in https://github.com/cms-cat/cms-root-style/pull/15
